-- Add reviewed_at to video_submissions
ALTER TABLE video_submissions 
ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP WITH TIME ZONE;

-- Add video_rate to influencers
ALTER TABLE influencers 
ADD COLUMN IF NOT EXISTS video_rate NUMERIC DEFAULT 0;

-- Create payments table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  influencer_id BIGINT REFERENCES influencers(id),
  video_submission_id BIGINT REFERENCES video_submissions(id),
  amount NUMERIC NOT NULL,
  payment_type TEXT DEFAULT 'fixed', -- 'fixed' or 'revenue_share'
  status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'failed'
  notes TEXT
);

-- Add RLS policies for payments
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Policy: Brands can insert payments (when approving videos)
CREATE POLICY "Brands can insert payments" 
ON payments 
FOR INSERT 
TO public 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM brands 
    WHERE brands.user_id = auth.uid()
  )
);

-- Policy: Influencers can view their own payments
CREATE POLICY "Influencers can view own payments" 
ON payments 
FOR SELECT 
TO public 
USING (
  influencer_id IN (
    SELECT id FROM influencers WHERE user_id = auth.uid()
  )
);

-- Policy: Brands can view payments they created (this is tricky without a brand_id on payments, 
-- but usually they view via campaign or influencer. For now, let's allow brands to see payments 
-- linked to their influencers/campaigns if needed, or just insert. 
-- Let's simply allow brands to read all payments for influencers they have worked with? 
-- Simplest for now: Brands can read all payments (might be too open, but ok for MVP) 
-- OR better: Link payment to brand via campaign? The payments table is simple. 
-- Let's stick to: Influencers view own. Brands insert. 
-- If brands need to view, we can add a policy later or join with other tables.
